// frontend/src/components/KommuneDetails/KommuneDetails.tsx
import { useQuery } from '@apollo/client';
import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Rating } from 'react-simple-star-rating';
import { GET_KOMMUNE } from '../../services/kommuneService';
import LoadingSpinner from '../LoadingSpinner/LoadingSpinner';
import './KommuneDetails.css';

export default function KommuneDetails({ refresh }: { refresh: boolean }) {
  // url param kommune/:id
  const { id } = useParams();

  // get kommune data from GraphQL
  const { loading, error, data, refetch } = useQuery(GET_KOMMUNE, {
    variables: { id: id },
  });

  // refetch data when the a new review is added to update kommune data
  useEffect(() => {
    if (refresh) {
      refetch();
    }
  }, [refresh]);

  // loading and error handling
  if (loading) return <LoadingSpinner />;
  if (error) return <div>Kommune ikke funnet</div>;

  return (
    <>
      {data && data.kommune && data.kommune && (
        <div className='detailsPage'>
          <div className='detailsPageTop'>
            <Link to='/'>
              <img
                data-cy='back-arrow'
                className='backArrow'
                src={require('../../assets/backArrow.png')}
                alt='backArrow'
              />
            </Link>
            <img
              data-cy='kommune-logo'
              src={data.kommune.logoUrl}
              className='weaponImg'
              alt='kommuneWeaponImage'
            />
            <h1 data-cy='kommune-name'>{data.kommune.name}</h1>
          </div>
          <div className='line'></div>
          <div className='kommuneDetails'>
            <div>
              <div className='rating'>
                <Rating
                  initialValue={data.kommune.averageRating}
                  readonly
                  size={30}
                />
                <div data-cy='kommune-rating' className='averageRating'>
                  {data.kommune.averageRating != 0
                    ? '(' + data.kommune.averageRating.toFixed(2) + ')'
                    : '(Ingen vurderinger)'}
                </div>
              </div>
              <label>📍 Fylke</label>
              <p data-cy='kommune-county'>{data.kommune.county.name}</p>
              <label>👨‍👩‍👧‍👧 Innbyggertall</label>
              <p data-cy='kommune-population'>{data.kommune.population}</p>
              <label>🏔 Areal</label>
              <p data-cy='kommune-area'>
                {data.kommune.areaInSquareKm}
                km<sup>2</sup>
              </p>
              <label>📝 Skriftspråk</label>
              <p data-cy='kommune-written-language'>{(data.kommune.writtenLanguage).charAt(0).toUpperCase() + (data.kommune.writtenLanguage).slice(1)}</p>
              <p>
                Les mer her:{' '}
                <a
                  href={data.kommune.snlLink}
                  target='_blank'
                  rel='noreferrer'>
                  {data.kommune.name}
                </a>
              </p>
            </div>
            <img
              data-cy='kommune-map'
              src={data.kommune.mapUrl}
              alt='kommuneMap'
              className='mapImg'
            />
          </div>
        </div>
      )}
    </>
  );
}

// frontend/src/components/KommuneDetails.vue
<template>
  <div className="detailsPage">
    <div className="detailsPageTop">
      <img
        :src="result.kommune.logoUrl"
        className="weaponImg"
        alt="kommuneWeaponImage"
      />
      <h1>{{ result.kommune.name }}</h1>
    </div>
    <div className="line"></div>
    <div className="kommuneDetails">
      <div>
          <div data-cy="kommune-rating" className="averageRating">
            {{
              result.kommune.averageRating != 0
                ? "(" + result.kommune.averageRating.toFixed(2) + ")"
                : "(Ingen vurderinger)"
            }}
          </div>
        </div>
        <label>📍 Fylke</label>
        <p data-cy="kommune-county">{{ result.kommune.county.name }}</p>
        <label>👨‍👩‍👧‍👧 Innbyggertall</label>
        <p data-cy="kommune-population">{{ result.kommune.population }}</p>
        <label>🏔 Areal</label>
        <p data-cy="kommune-area">
          {{ result.kommune.areaInSquareKm }} km<sup>2</sup>
        </p>
        <label>📝 Skriftspråk</label>
        <p data-cy="kommune-written-language">
          {{
            result.kommune.writtenLanguage.charAt(0).toUpperCase() +
            result.kommune.writtenLanguage.slice(1)
          }}
        </p>
        <p>
          Les mer her:{' '}
          <a href="{result.kommune.snlLink}" target="_blank" rel="noreferrer">
            {{ result.kommune.name }}
          </a>
        </p>
      </div>
      <img :src="result.kommune.mapUrl" alt="kommuneMap" className="mapImg" />
    </div>
  </div>
</template>
<script setup="ts" lang="ts">
import kommuneService from "@/services/kommuneService";
import { useQuery } from "@vue/apollo-composable";
import { useRoute } from "vue-router";

// url param kommune/:id
const id = useRoute().params.id;

const { result, loading, error } = useQuery(kommuneService.GET_KOMMUNE, () => ({
  id: id,
}));
</script>

<style scoped>
p {
  font-size: 18px;
  margin-top: 0px;
}

label {
  font-size: 16px;
  font-weight: bold;
}

.detailsPage {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 10px 0;
}

.detailsPageTop {
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 10px;
}

.kommuneDetails {
  display: flex;
  flex-direction: row;
  justify-content: center;
  gap: 10vw;
  margin-top: 20px;
  align-items: center;
}

.backArrow {
  max-width: 60px;
  position: absolute;
  left: 5%;
  margin-top: -15px;
  cursor: pointer;
}

.rating {
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 5px;
  margin-bottom: 10px;
}

.weaponImg {
  width: 50px;
}

.mapImg {
  width: 20%;
  height: 20%;
}

.line {
  background-color: #405a7e;
  height: 2px;
  width: clamp(100px, calc(100vw - 50px), 600px);
}

@media screen and (max-width: 500px) {
  .kommuneDetails {
    flex-direction: column;
    gap: 0px;
  }

  .mapImg {
    width: 150px;
  }

  .backArrow {
    max-width: 40px;
  }

  .weaponImg {
    width: 30px;
    z-index: 1;
  }

  h1 {
    font-size: 24px;
  }

  p {
    font-size: 16px;
  }
}
</style>
