// frontend/src/components/InputFields.vue
<template>
  <n-space vertical>
    <n-select
      v-model:value="countyStore.county"
      :options="countyOptions"
      @update:value="changeCounty"
      :clearable="true"
    />
    <n-select
      v-model:value="sortStore.sort"
      :options="sortOptions"
      @update:value="changeSort"
      :clearable="true"
    />
  </n-space>
</template>

<script setup="ts" lang="ts">
import { useCountyStore } from "@/stores/county";
import { useSortStore } from "@/stores/sort";
import { usePageStore } from "@/stores/page";
import { NSpace, NSelect } from "naive-ui";
import { ref } from "vue";
import { useQuery } from "@vue/apollo-composable";
import GET_ALL_COUNTIES from "../services/countyService";

// global states from stores
const countyStore = useCountyStore();
const sortStore = useSortStore();
const pageStore = usePageStore();

// options for county dropdown
const countyOptions = ref([]);

// options for sort dropdown
const sortOptions = [
  { label: "Areal høy-lav", value: "Areal høy-lav" },
  { label: "Areal lav-høy", value: "Areal lav-høy" },
  { label: "Befolkning høy-lav", value: "Befolkning høy-lav" },
  { label: "Befolkning lav-høy", value: "Befolkning lav-høy" },
  { label: "Rangering høy-lav", value: "Rangering høy-lav" },
  { label: "Rangering lav-høy", value: "Rangering lav-høy" },
];

// get all counties sorted alphabetically, with value of countyId
useQuery(GET_ALL_COUNTIES).onResult((res) => {
  countyOptions.value = res.data.counties
    .map((county: { name: string; __typename: string; _id: string }) => {
      return {
        label: county.name,
        value: county._id,
      };
    })
    .sort((a: { label: string }, b: { label: string }) =>
      a.label.localeCompare(b.label)
    );
});

// set page to 1 when county is changed
function changeCounty() {
  pageStore.updatePage(1);
}

// set page to 1 when sort is changed
function changeSort() {
  pageStore.updatePage(1);
}
</script>

<style scoped>
.n-select {
  width: 200px;
}
</style>

// frontend/src/components/InputFields/InputFields.tsx
import './InputFields.css';
import { Select } from '@mantine/core';
import { useAppDispatch, useAppSelector } from '../../redux/hooks';
import { updateCounty } from '../../redux/countyReducer';
import { updateFilter } from '../../redux/filterReducer';
import { GET_ALL_COUNTIES } from '../../services/countyService';
import { useQuery } from '@apollo/client';
import { updatePage } from '../../redux/pageReducer';

export default function InputFields() {
  // global states from Redux
  const county = useAppSelector((state) => state.countyInput.county);
  const filter = useAppSelector((state) => state.filterInput.filter);
  const dispatch = useAppDispatch();

  // update county on change and set page to 1
  const changeCounty = (county: string) => {
    dispatch(updateCounty(county));
    dispatch(updatePage(1));
  };

  // update filter on change and set page to 1
  const changeFilter = (filter: string) => {
    dispatch(updateFilter(filter));
    dispatch(updatePage(1));
  };

  // get counties from GraphQL
  const { data } = useQuery(GET_ALL_COUNTIES);

  // counties sorted alphabetically, with value of countyId
  const counties = data?.counties
    .map((county: { name: string; __typename: string; _id: string }) => {
      return { label: county.name, value: county._id };
    })
    .sort((a: { label: string }, b: { label: string }) =>
      a.label > b.label ? 1 : -1
    );

  return (
    <div className='inputFields'>
      <div className='dropdown'>
        {data?.counties ? (
          <Select
            defaultValue={county}
            label='Filtrer på fylke'
            data={counties}
            searchable
            clearable
            onChange={changeCounty}
            dropdownPosition='bottom'
            data-cy='inp-filter-county'
          />
        ) : null}
        <Select
          defaultValue={filter}
          data-cy='inp-sort'
          label='Sorter'
          data={[
            'Areal høy-lav',
            'Areal lav-høy',
            'Befolkning høy-lav',
            'Befolkning lav-høy',
            'Rangering høy-lav',
            'Rangering lav-høy',
          ]}
          clearable
          onChange={changeFilter}
          dropdownPosition='bottom'
        />
      </div>
    </div>
  );
}
